# Generated by Django 5.2.7 on 2026-03-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_doctor_bio_alter_customuser_role_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(default=0)),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('company_name', models.CharField(max_length=100)),
                ('storage_block', models.CharField(help_text='e.g., Block A-10', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('pharmacist', 'Pharmacist'), ('lab_tech', 'Lab Technician')], default='patient', max_length=15),
        ),
    ]
