# Generated by Django 5.2.7 on 2026-03-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_labtest_labrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='sold_count',
            field=models.PositiveIntegerField(default=0, help_text='Total units dispensed/sold'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='company_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='count',
            field=models.PositiveIntegerField(help_text='Current remaining stock'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='storage_block',
            field=models.CharField(help_text="Where it's stored, e.g., 'A-10'", max_length=50),
        ),
    ]
