# Generated by Django 5.2.7 on 2026-03-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_medicine_sold_count_alter_medicine_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_dispensed',
            field=models.BooleanField(default=False, help_text='Whether medicines have been dispensed by the pharmacist'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicines',
            field=models.JSONField(default=list, help_text="List of medicines, e.g., [{'name': 'Paracetamol', 'dosage': '500mg', 'quantity': 1}]"),
        ),
    ]
