# Generated by Django 5.2.7 on 2026-03-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_prescription_is_dispensed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='token_number',
            field=models.PositiveIntegerField(blank=True, help_text='Sequential token number for the doctor on this date', null=True),
        ),
    ]
