# Generated by Django 5.2.7 on 2026-03-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_appointment_token_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='report_file',
            field=models.FileField(blank=True, help_text='Patient lab report in PDF format', null=True, upload_to='lab_reports/'),
        ),
    ]
